[package]
name = "touchHLE"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mach_object = "0.1.17"
plist = "1.3.1"
# sdl2 crates pinned at 0.35.1 because static linking seems to be broken for
# 0.35.2 on macOS (build errors about undefined symbols for
# _CHHapticDynamicParameterIDHapticIntensityControl etc)
sdl2 = { version = "=0.35.1", features = ["bundled", "static-link"] }
sdl2-sys = "=0.35.1"

[build-dependencies]
cc = "1.0.77"
